name: Auto Tests
on:
  push:
    paths:
    - 'app/**'
    - 'core/**'
    - 'images/**'
    - 'qgsquick/**'
    - 'scripts/**'
    - '.github/workflows/autotests.yml'

  release:
    types:
      - published

env:
  TEST_MERGIN_URL: https://test.dev.cloudmergin.com/
  TEST_API_USERNAME: test_inputapp
  TEST_API_PASSWORD: ${{ secrets.MERGINTEST_API_PASSWORD }}
  QT_VERSION: 5.14.2
  QMAKE_MACOSX_DEPLOYMENT_TARGET: 10.13.0
  INPUT_SDK_VERSION: mac-20211110-23

jobs:
  tests:
    if: ( github.repository == 'lutraconsulting/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    runs-on: macos-10.15
    steps:
      - name: Checkout Input
        uses: actions/checkout@v2
        with:
          path: input

      - name: install brew deps
        run: |
          brew install lcov

      - name: Extract Mergin API_KEY
        env:
          MERGINSECRETS_DECRYPT_KEY: ${{ secrets.MERGINSECRETS_DECRYPT_KEY }}
        run: |
          cd input/core/
          /usr/local/opt/openssl@1.1/bin/openssl \
              aes-256-cbc -d \
              -in merginsecrets.cpp.enc \
              -out merginsecrets.cpp \
              -k "$MERGINSECRETS_DECRYPT_KEY" \
              -md md5

      # Qt
      - name: Cache Qt
        id: cache-qt
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-QtCache-v1-${{ env.QT_VERSION }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          dir: ${{ github.workspace }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      
      # Input SDK
      - name: Cache Input-SDK
        id: cache-input-sdk
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ github.workspace }}/input-sdk
          key: ${{ runner.os }}-input-sdk-v2-${{ env.INPUT_SDK_VERSION }}

      - name: Install Input-SDK
        if: steps.cache-input-sdk.outputs.cache-hit != 'true'
        run: |
          wget -O \
            input-sdk.tar.gz \
            https://github.com/lutraconsulting/input-sdk/releases/download/${{ env.INPUT_SDK_VERSION }}/input-sdk-qt-${{ env.QT_VERSION }}-${{ env.INPUT_SDK_VERSION }}.tar.gz
          mkdir -p ${{ github.workspace }}/input-sdk
          cd ${{ github.workspace }}/input-sdk
          tar -xvzf input-sdk.tar.gz
          ls ${{ github.workspace }}/input-sdk
          
      # Build Input App
      - name: Export app/config.pri
        run: |
          touch ./app/config.pri
          echo -e "android {"  >> ./app/config.pri
          echo -e "  INPUT_SDK_PATH = ${{ github.workspace }}/input-sdk"  >> ./app/config.pri
          echo -e "  QMAKE_MACOSX_DEPLOYMENT_TARGET = ${{ env.QMAKE_MACOSX_DEPLOYMENT_TARGET }}"  >> ./app/config.pri
          echo -e "  QGIS_QUICK_DATA_PATH = ${{ github.workspace }}/input/app/android/assets/qgis-data"  >> ./app/config.pri
          echo -e "  QMAKE_CXXFLAGS += --coverage"  >> ./app/config.pri
          echo -e "  QMAKE_LFLAGS += --coverage "  >> ./app/config.pri
          echo -e "}"  >> ./app/config.pri		  
          cat ./app/config.conf
          
      - name: build Input
        run: |
          cp input/scripts/ci/config.pri input/app/config.pri

          mkdir -p build-Input
          cd build-Input
          /opt/Qt/${QT_VERSION}/clang_64/bin/qmake \
            ../input/app/input.pro \
            CONFIG+=debug \
            CONFIG+=qtquickcompiler

          make
          install_name_tool -add_rpath /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/lib/ Input.app/Contents/MacOS/Input
          install_name_tool -add_rpath /opt/INPUT/input-sdk-mac-${SDK_VERSION}/stage/mac/lib Input.app/Contents/MacOS/Input

      - name: run tests
        run: |
          cd build-Input/
          ../input/scripts/run_all_tests.bash ./Input.app/Contents/MacOS/Input

      - name: build lcov summary
        run: |
          cd build-Input
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '*/merginsecrets.cpp' '*/test/*' '/usr/*' '/Applications/*' '/opt/*' '*build-Input/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build-Input/coverage.info
