name: QgsQuick
on: [push]
env:
  QGIS_COMMIT_HASH: a559212bbda3af37300c17997b826751318299cd

jobs:
  qgsquick_up_to_date:
    if: ( github.repository == 'lutraconsulting/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: download qgis
        run: |
          git clone https://github.com/qgis/QGIS.git --depth 1
          cd QGIS
          git fetch --depth 1 origin ${QGIS_COMMIT_HASH}
          git checkout FETCH_HEAD
          cd ..

      - name: run check the qgsquick is up-to-date
        run: |
          ./scripts/copy_qgsquick.bash QGIS/
